services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true

  postgres:
    container_name: container-pg
    image: postgres
    hostname: host.docker.internal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
